name: build

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        version:
        - binary:stable
        # - devel
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.nimversion }}
    
    # - name: Install Linux deps
    #   if: runner.os == 'Linux'
    #   run: |
    #     sudo apt-get update -q
    # - name: Install macOS deps
    #   if: runner.os == 'macOS'
    #   run: |
    #     brew update
    #     brew install libsodium
    
    - name: Test
      run: |
        nimble refresh
        nimble test
